name: Full CI/CD Pipeline for SonarCloud, Azure Web App, and Cloudflare Pages

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. SonarCloud Analysis Job
  sonarcloud-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Run SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=amankrs21_test-cicd
            -Dsonar.organization=amankrs21
          projectBaseDir: .

  # 2. Express App Hosting Job (depends on SonarCloud success, but only runs on push to `main`)
  express-deployment:
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    if: github.ref == 'refs/heads/main' # Only run on push to `main` branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies for Express app
        run: npm install
        working-directory: ./server

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  # 3. Deploy to Azure Web App (depends on Express app deployment success)
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: express-deployment
    if: github.ref == 'refs/heads/main' # Only run on push to `main` branch

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C893E2C4A148480F887E7FC7AE540921 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D0B6632477BE4425A279ED0D006341AF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B302598FD9F549A3B424502161CA248F }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test-cicd'
          slot-name: 'Production'
          package: ./server

  # 4. React App Hosting to Cloudflare (depends on Azure Web App deployment success)
  react-deployment:
    runs-on: ubuntu-latest
    needs: deploy-to-azure
    if: github.ref == 'refs/heads/main' # Only run on push to `main` branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies for React app
        run: npm install
        working-directory: ./client

      - name: Build React app
        run: npm run build
        working-directory: ./client

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'test-cicd'
          directory: 'client/dist'
